version: "3"

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "test"
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "12345"
    volumes:
      - ./init/.:/docker-entrypoint-initdb.d
    ports:
      - "5435:5432"

  weather:
    build: ./app
    restart: always
    depends_on:
      - postgres
    ports:
      - "8081:8081"
    environment:
      PSQL_USERNAME: "test"
      PSQL_PASSWORD: "12345"
      PSQL_HOST: "localhost"
      PSQL_PORT: "5435"
      PSQL_DATABASE: "test"
      API_KEY: "55416e29c70a43557ee6918eb1b5322a"
